spring:
  datasource:
    url: jdbc:mysql://localhost:3306/agoda
    username: 'root'
    password: '0612'
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

cors:
  allow-origins:
    - "http://localhost:5173"
    - "http://localhost:8080"
