spring:
  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
spring.devtools.restart.enabled: false

cors:
  allow-origins:
    - "*"
kakao:
  client-id: ${kakao.client-id}
  redirect-uri: ${kakao.redirect-uri}
  javascript-key: ${kakao.javascript-key}

jwt:
  secret-key: ${jwt.secret-key}
cloud:
  aws:
    s3:
      bucket: ${cloud.aws.s3.bucket}
    credentials:
      access-key: ${cloud.aws.credentials.access-key}
      secret-key: ${cloud.aws.credentials.secret-key}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
